[tool.poetry]
name = "jive-image-viewer"
version = "0.7.6"
description = "A general purpose, cross-platform image viewer with some built-in NSFW support."
authors = ["Jabba Laci <jabba.laci@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
imgurpython = "^1.1.7"
pyqt5 = "^5.15.6"
appdirs = "^1.4.4"
bs4 = "^0.0.1"
psutil = "^5.9.0"
pyyaml = "^5.4.1"
PyTumblr = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pyinstaller = "^4.5.1"
pynt = "^0.8.2"
mypy = "^0.812"
PyQt5-stubs = "^5.15.2.0"
poetryup = "^0.3.15"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
