[tool.poetry]
name = "jive-image-viewer"
version = "0.7.5"
description = "A general purpose, cross-platform image viewer with some built-in NSFW support."
authors = ["Jabba Laci <jabba.laci@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
imgurpython = "^1.1"
pyqt5 = "^5.14"
appdirs = "^1.4"
bs4 = "^0.0.1"
psutil = "^5.6"
pyyaml = "^5.2"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
pyinstaller = "^4.0"
pynt = "^0.8.2"
mypy = "^0.790"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
