# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jive/folding.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.sequenceUrlEdit = QtWidgets.QLineEdit(Dialog)
        self.sequenceUrlEdit.setGeometry(QtCore.QRect(20, 20, 601, 30))
        self.sequenceUrlEdit.setObjectName("sequenceUrlEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(230, 60, 191, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.unpackButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.unpackButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unpackButton.setIcon(icon)
        self.unpackButton.setIconSize(QtCore.QSize(36, 36))
        self.unpackButton.setObjectName("unpackButton")
        self.horizontalLayout.addWidget(self.unpackButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.packButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.packButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/assets/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.packButton.setIcon(icon1)
        self.packButton.setIconSize(QtCore.QSize(36, 36))
        self.packButton.setObjectName("packButton")
        self.horizontalLayout.addWidget(self.packButton)
        self.urlListEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.urlListEdit.setGeometry(QtCore.QRect(20, 135, 601, 281))
        self.urlListEdit.setObjectName("urlListEdit")
        self.sequenceUrlOpen = QtWidgets.QPushButton(Dialog)
        self.sequenceUrlOpen.setGeometry(QtCore.QRect(570, 70, 51, 30))
        self.sequenceUrlOpen.setObjectName("sequenceUrlOpen")
        self.sequenceUrlClear = QtWidgets.QPushButton(Dialog)
        self.sequenceUrlClear.setGeometry(QtCore.QRect(510, 70, 51, 30))
        self.sequenceUrlClear.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/assets/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sequenceUrlClear.setIcon(icon2)
        self.sequenceUrlClear.setObjectName("sequenceUrlClear")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(533, 50, 21, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.sequenceUrlClipboard = QtWidgets.QPushButton(Dialog)
        self.sequenceUrlClipboard.setGeometry(QtCore.QRect(20, 70, 51, 30))
        self.sequenceUrlClipboard.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/assets/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sequenceUrlClipboard.setIcon(icon3)
        self.sequenceUrlClipboard.setIconSize(QtCore.QSize(24, 24))
        self.sequenceUrlClipboard.setObjectName("sequenceUrlClipboard")
        self.urlListClear = QtWidgets.QPushButton(Dialog)
        self.urlListClear.setGeometry(QtCore.QRect(507, 438, 51, 30))
        self.urlListClear.setText("")
        self.urlListClear.setIcon(icon2)
        self.urlListClear.setObjectName("urlListClear")
        self.urlListClipboard = QtWidgets.QPushButton(Dialog)
        self.urlListClipboard.setGeometry(QtCore.QRect(17, 438, 51, 30))
        self.urlListClipboard.setText("")
        self.urlListClipboard.setIcon(icon3)
        self.urlListClipboard.setIconSize(QtCore.QSize(24, 24))
        self.urlListClipboard.setObjectName("urlListClipboard")
        self.urlListOpen = QtWidgets.QPushButton(Dialog)
        self.urlListOpen.setGeometry(QtCore.QRect(567, 438, 51, 30))
        self.urlListOpen.setObjectName("urlListOpen")
        self.urlListPasteClipboard = QtWidgets.QPushButton(Dialog)
        self.urlListPasteClipboard.setGeometry(QtCore.QRect(80, 438, 41, 30))
        self.urlListPasteClipboard.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/assets/paste_from_clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.urlListPasteClipboard.setIcon(icon4)
        self.urlListPasteClipboard.setIconSize(QtCore.QSize(36, 36))
        self.urlListPasteClipboard.setObjectName("urlListPasteClipboard")
        self.sequenceUrlPasteClipboard = QtWidgets.QPushButton(Dialog)
        self.sequenceUrlPasteClipboard.setGeometry(QtCore.QRect(80, 70, 41, 30))
        self.sequenceUrlPasteClipboard.setText("")
        self.sequenceUrlPasteClipboard.setIcon(icon4)
        self.sequenceUrlPasteClipboard.setIconSize(QtCore.QSize(36, 36))
        self.sequenceUrlPasteClipboard.setObjectName("sequenceUrlPasteClipboard")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(270, 438, 107, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/assets/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon5)
        self.cancelButton.setIconSize(QtCore.QSize(24, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 42, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(97, 42, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(592, 42, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(38, 409, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(97, 409, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(529, 417, 21, 18))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(587, 409, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Dialog)
        self.cancelButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.sequenceUrlEdit, self.unpackButton)
        Dialog.setTabOrder(self.unpackButton, self.packButton)
        Dialog.setTabOrder(self.packButton, self.sequenceUrlOpen)
        Dialog.setTabOrder(self.sequenceUrlOpen, self.urlListEdit)
        Dialog.setTabOrder(self.urlListEdit, self.urlListOpen)
        Dialog.setTabOrder(self.urlListOpen, self.sequenceUrlClipboard)
        Dialog.setTabOrder(self.sequenceUrlClipboard, self.sequenceUrlClear)
        Dialog.setTabOrder(self.sequenceUrlClear, self.urlListClipboard)
        Dialog.setTabOrder(self.urlListClipboard, self.urlListClear)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "URL folding / unfolding"))
        self.sequenceUrlEdit.setPlaceholderText(_translate("Dialog", "sequence URL"))
        self.unpackButton.setToolTip(_translate("Dialog", "unfold (unpack)"))
        self.packButton.setToolTip(_translate("Dialog", "fold (pack)"))
        self.urlListEdit.setPlaceholderText(_translate("Dialog", "list of URLs"))
        self.sequenceUrlOpen.setToolTip(_translate("Dialog", "open images in JiVE"))
        self.sequenceUrlOpen.setText(_translate("Dialog", "Open"))
        self.sequenceUrlClear.setToolTip(_translate("Dialog", "clear"))
        self.label_2.setText(_translate("Dialog", "|"))
        self.sequenceUrlClipboard.setToolTip(_translate("Dialog", "copy to clipboard"))
        self.urlListClear.setToolTip(_translate("Dialog", "clear"))
        self.urlListClipboard.setToolTip(_translate("Dialog", "copy to clipboard"))
        self.urlListOpen.setToolTip(_translate("Dialog", "open images in JiVE"))
        self.urlListOpen.setText(_translate("Dialog", "Open"))
        self.urlListPasteClipboard.setToolTip(_translate("Dialog", "paste from clipboard"))
        self.sequenceUrlPasteClipboard.setToolTip(_translate("Dialog", "paste from clipboard"))
        self.cancelButton.setText(_translate("Dialog", " &Cancel"))
        self.label_9.setText(_translate("Dialog", "↓"))
        self.label_10.setText(_translate("Dialog", "↑"))
        self.label_12.setText(_translate("Dialog", "↓"))
        self.label_11.setText(_translate("Dialog", "↓"))
        self.label_13.setText(_translate("Dialog", "↑"))
        self.label_3.setText(_translate("Dialog", "|"))
        self.label_14.setText(_translate("Dialog", "↓"))

from jive import icons_rc
